name: Market Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9,13,19 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kütüphaneleri Kur
        run: |
          pip install -r requirements.txt

      - name: Botu Çalıştır
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          python main.py
